### ISSUE TITLE
There should be no STOP handler

### ISSUE THREAD

**Issue by troykelly** [home-buddy/express-appengine-handlers#16]
The stop handler should not be handled in this way by express. A request to /_ah/stop bypasses the handler (per documentation):

> The /_ah/stop request bypasses normal handling logic and cannot be handled by user code; its sole purpose is to invoke the shutdown hook.

Exposing /_ah/stop like this means that anybody can call this function and stop (which results in a restart) of the App Engine instance.

**Comment by SpainTrain** [comment]
Closed by https://github.com/homezen/express-appengine-handlers/pull/17
